### ISSUE TITLE
Error setting up entry UI Lovelace Minimalist for ui_lovelace_minimalist

### ISSUE THREAD

**Issue by fmhongi** [UI-Lovelace-Minimalist/UI#1003]
此错误来自自定义集成。

Logger: homeassistant.config_entries
Source: custom_components/ui_lovelace_minimalist/utils/decode.py:7
Integration: UI Lovelace Minimalist (documentation, issues)
First occurred: 17:38:59 (1 occurrences)
Last logged: 17:38:59

Error setting up entry UI Lovelace Minimalist for ui_lovelace_minimalist
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 124, in async_setup_entry
    return await async_initialize_integration(hass=hass, config_entry=config_entry)
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 104, in async_initialize_integration
    startup_result = await async_startup()
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 90, in async_startup
    await ulm.configure_community_cards()
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 280, in configure_community_cards
    content=await self.async_github_get_file(
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 178, in async_github_get_file
    return decode_content(response.data.content)
  File "/config/custom_components/ui_lovelace_minimalist/utils/decode.py", line 7, in decode_content
    return b64decode(bytearray(content, "utf-8")).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by Marcoevich** [comment]
Got the same issue here, new install of UI Lovalace Minimalist trough HACS:

Logger: homeassistant.config_entries
Source: custom_components/ui_lovelace_minimalist/utils/decode.py:7
Integration: UI Lovelace Minimalist ([documentation](https://ui-lovelace-minimalist.github.io/UI/), [issues](https://github.com/UI-Lovelace-Minimalist/UI/issues))
First occurred: 00:12:13 (1 occurrences)
Last logged: 00:12:13

Error setting up entry UI Lovelace Minimalist for ui_lovelace_minimalist
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 124, in async_setup_entry
    return await async_initialize_integration(hass=hass, config_entry=config_entry)
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 104, in async_initialize_integration
    startup_result = await async_startup()
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 90, in async_startup
    await ulm.configure_community_cards()
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 280, in configure_community_cards
    content=await self.async_github_get_file(
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 178, in async_github_get_file
    return decode_content(response.data.content)
  File "/config/custom_components/ui_lovelace_minimalist/utils/decode.py", line 7, in decode_content
    return b64decode(bytearray(content, "utf-8")).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by tyfin** [comment]
I am also getting this error:

Logger: homeassistant.config_entries
Source: custom_components/ui_lovelace_minimalist/utils/decode.py:7 
Integration: UI Lovelace Minimalist ([documentation](https://ui-lovelace-minimalist.github.io/UI/), [issues](https://github.com/UI-Lovelace-Minimalist/UI/issues)) 
First occurred: 12:16:46 AM (1 occurrences) 
Last logged: 12:16:46 AM

Error setting up entry for ui_lovelace_minimalist
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 124, in async_setup_entry
    return await async_initialize_integration(hass=hass, config_entry=config_entry)
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 104, in async_initialize_integration
    startup_result = await async_startup()
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 90, in async_startup
    await ulm.configure_community_cards()
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 280, in configure_community_cards
    content=await self.async_github_get_file(
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 178, in async_github_get_file
    return decode_content(response.data.content)
  File "/config/custom_components/ui_lovelace_minimalist/utils/decode.py", line 7, in decode_content
    return b64decode(bytearray(content, "utf-8")).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
