### ISSUE TITLE
Update 2023.02

### ISSUE THREAD

**Issue by mdb17** [UI-Lovelace-Minimalist/UI#1156]
**Describe the bug**
After updating to 2023.02 I am getting the following error in the logs and it is failing to load. 

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/ui_lovelace_minimalist/base.py:216
Integration: UI Lovelace Minimalist (documentation, issues)
First occurred: 2:43:03 PM (1 occurrences)
Last logged: 2:43:03 PM

Error setting up entry UI Lovelace Minimalist for ui_lovelace_minimalist
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 124, in async_setup_entry
    return await async_initialize_integration(hass=hass, config_entry=config_entry)
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 104, in async_initialize_integration
    startup_result = await async_startup()
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 89, in async_startup
    await ulm.fetch_cards()
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 221, in fetch_cards
    response = await self.async_github_api_method(
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 216, in async_github_api_method
    raise Exception(_exception)
Exception: Timeout of 20 reached while waiting for https://api.github.com/repos/UI-Lovelace-Minimalist/UI/contents/custom_cards
```

**Comment by wilbiev** [comment]
Fixed in new release v1.3.11
