### ISSUE TITLE
Error setting up entry

### ISSUE THREAD

**Issue by marvandorth** [UI-Lovelace-Minimalist/UI#1294]
Updated ULM manually to v1.3.5 and updates Home Assistant to 2023.5.1 afterwards. Now I receive errors on startup;

``
Error setting up entry UI Lovelace Minimalist for ui_lovelace_minimalist
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 124, in async_setup_entry
    return await async_initialize_integration(hass=hass, config_entry=config_entry)
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 104, in async_initialize_integration
    startup_result = await async_startup()
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 90, in async_startup
    await ulm.configure_community_cards()
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 280, in configure_community_cards
    content=await self.async_github_get_file(
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 178, in async_github_get_file
    return decode_content(response.data.content)
  File "/config/custom_components/ui_lovelace_minimalist/utils/decode.py", line 7, in decode_content
    return b64decode(bytearray(content, "utf-8")).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
``
Did a reinstall of ULM but to no avail. What could go wrong?

**Comment by Ozel0t-G** [comment]
Same here.
After restart Home Assistant i got the same error ...

**Comment by thstorm** [comment]
Same here

**Comment by Ozel0t-G** [comment]
it is totally annoying every time i have to restart Home Assistant The Dashboard dont work at all....

**Comment by marvandorth** [comment]
Whenever I restart HA, ULM is broken but after a complete wipe of the integration and setting it up again it seems to be fixed until the next restart of HA.

**Comment by wilbiev** [comment]
Fixed in new releases
