### ISSUE TITLE
Minimal List not loading

### ISSUE THREAD

**Issue by nmeliasp** [UI-Lovelace-Minimalist/UI#1359]
After installing an update to Home Assistant, minimalist stopped loading and found the error below in the logs. Please help!

Logger: homeassistant.config_entries
Source: custom_components/ui_lovelace_minimalist/utils/decode.py:7
Integration: UI Lovelace Minimalist ([documentation](https://ui-lovelace-minimalist.github.io/UI/), [issues](https://github.com/UI-Lovelace-Minimalist/UI/issues))
First occurred: 3:00:21 PM (1 occurrences)
Last logged: 3:00:21 PM

Error setting up entry UI Lovelace Minimalist for ui_lovelace_minimalist
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 124, in async_setup_entry
    return await async_initialize_integration(hass=hass, config_entry=config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 104, in async_initialize_integration
    startup_result = await async_startup()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 90, in async_startup
    await ulm.configure_community_cards()
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 280, in configure_community_cards
    content=await self.async_github_get_file(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 178, in async_github_get_file
    return decode_content(response.data.content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/utils/decode.py", line 7, in decode_content
    return b64decode(bytearray(content, "utf-8")).decode()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by wilbiev** [comment]
Cleaning-up issue list. Let me know if this issue needs to be reopened. Should be fixed in current release.
