### ISSUE TITLE
I have this in the journal of HA core after freeze of HA and auto restart 

### ISSUE THREAD

**Issue by alainvdu69** [UI-Lovelace-Minimalist/UI#1507]
I don't know if this could explain what sometimes happen since one or 2 months : i'm using VSS when updating YAML files and i suddenly lost HA ...
I've to wait and HA restart automaticaly.

And i've just discovered this in the journal of HA Core

2024-06-17 15:34:31.549 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'ui_lovelace_minimalist' at custom_components/ui_lovelace_minimalist/base.py, line 498: shutil.copytree( (offender: /usr/local/lib/python3.12/shutil.py, line 262: with open(dst, 'wb') as fdst:), please create a bug report at https://github.com/UI-Lovelace-Minimalist/UI/issues
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
result = await _async_setup_component(hass, domain, config)
File "/usr/src/homeassistant/homeassistant/setup.py", line 447, in _async_setup_component
await asyncio.gather(
File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in <genexpr>
create_eager_task(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
return Task(coro, loop=loop, name=name, eager_start=True)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
await self.async_setup(hass, integration=integration)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 124, in async_setup_entry
return await async_initialize_integration(hass=hass, config_entry=config_entry)
File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 104, in async_initialize_integration
startup_result = await async_startup()
File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 93, in async_startup
not await ulm.configure_ulm()
File "/config/custom_components/ui_lovelace_minimalist/base.py", line 498, in configure_ulm
shutil.copytree(

**Comment by bdraco** [comment]
https://developers.home-assistant.io/docs/asyncio_blocking_operations#open

**Comment by wilbiev** [comment]
Fixed in new release v1.3.11
