### ISSUE TITLE
Enable the ability to configure community cards with this integrations, Does require GitHub authentication//Enabling failed

### ISSUE THREAD

**Issue by xiasi0** [UI-Lovelace-Minimalist/UI#1521]
```
Error unloading entry UI Lovelace Minimalist for ui_lovelace_minimalist
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 801, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 162, in async_unload_entry
    return await async_initialize_integration(hass=hass, config_entry=config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 103, in async_initialize_integration
    startup_result = await async_startup()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 90, in async_startup
    await ulm.configure_community_cards()
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 302, in configure_community_cards
    content=await self.async_github_get_file(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 182, in async_github_get_file
    return decode_content(response.data.content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/utils/decode.py", line 7, in decode_content
    return b64decode(bytearray(content, "utf-8")).decode()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by wilbiev** [comment]
This looks to be related to issue #1569. Can you confirm the "custom_card_heat_pump" was selected?
