### ISSUE TITLE
Failed to load on startup

### ISSUE THREAD

**Issue by ShadyMCShadesen** [UI-Lovelace-Minimalist/UI#1569]
**Describe the bug**
I think the cause of the problem is the community cards. If I have activated these and then restart, the integration cannot be loaded. However, if I go into the integration settings during operation and deactivate the community cards and then immediately reactivate them, the dashboard works.(although the integration list then says "could not be unloaded")

**To Reproduce**
- Install integration
- Activate community cards and select all
- Reboot home assistant

**Expected behavior**
The dashboard is accessible after reboot

**Related Logs**
Logger: homeassistant.config_entries
Quelle: config_entries.py:640
Erstmals aufgetreten: 21. Dezember 2024 um 21:43:18 (2 Vorkommnisse)
Zuletzt protokolliert: 11:02:07

Error setting up entry UI Lovelace Minimalist for ui_lovelace_minimalist
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 125, in async_setup_entry
    return await async_initialize_integration(hass=hass, config_entry=config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 103, in async_initialize_integration
    startup_result = await async_startup()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 90, in async_startup
    await ulm.configure_community_cards()
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 303, in configure_community_cards
    content=await self.async_github_get_file(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        filename=f.path
        ^^^^^^^^^^^^^^^
    ),
    ^
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 183, in async_github_get_file
    return decode_content(response.data.content)
  File "/config/custom_components/ui_lovelace_minimalist/utils/decode.py", line 7, in decode_content
    return b64decode(bytearray(content, "utf-8")).decode()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by wilbiev** [comment]
I was able to reproduce this behaviour when I enabled custom cards without a GitHub account. When installing the UI Minimalist integration you need to select the option to 'Enable GitHub'. Otherwise you are not able to use the custom cards.

**Comment by ShadyMCShadesen** [comment]
This is weird, GitHub should be enabled and authenticated. It worked over a year, is there a possibility that I have to reauthenticate? Although I don't get a pop-up asking for this.

**Comment by ShadyMCShadesen** [comment]
Still the same error even after complete reinstalling the integration

Logger: homeassistant.config_entries
Quelle: config_entries.py:640
Erstmals aufgetreten: 30. Dezember 2024 um 23:11:01 (2 Vorkommnisse)
Zuletzt protokolliert: 13:15:40

Error setting up entry UI Lovelace Minimalist for ui_lovelace_minimalist
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 128, in async_setup_entry
    return await async_initialize_integration(hass=hass, config_entry=config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 106, in async_initialize_integration
    startup_result = await async_startup()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ui_lovelace_minimalist/__init__.py", line 93, in async_startup
    await ulm.configure_community_cards()
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 304, in configure_community_cards
    content=await self.async_github_get_file(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        filename=f.path
        ^^^^^^^^^^^^^^^
    ),
    ^
  File "/config/custom_components/ui_lovelace_minimalist/base.py", line 184, in async_github_get_file
    return decode_content(response.data.content)
  File "/config/custom_components/ui_lovelace_minimalist/utils/decode.py", line 8, in decode_content
    return b64decode(bytearray(content, "utf-8")).decode()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by Serdar2808** [comment]
Try reinstalling the integration in Settings/Devices and dont select "custom_card_heat_pump"  in the configuration.

**Comment by ShadyMCShadesen** [comment]
> Try reinstalling the integration in Settings/Devices and dont select "custom_card_heat_pump"  in the configuration.

Yeah I've selected only the custom_cards I really need and now it works fine.
