### ISSUE TITLE
Missing panels "ha-panel-lovelace" and "paper-slider"

### ISSUE THREAD

**Issue by sergivillar** [UI-Lovelace-Minimalist/UI#1586]
Hey all,

**Describe the bug**
I made a fresh installation of HA and Lovelace, everything works as expected (I think, still missing some config on my home views) but when I look at the console I'm seeing the following errors.

```
mini-media-player.js:689 Uncaught (in promise) TypeError: Class extends value undefined is not a constructor or null
    at mini-media-player.js:689:27057
(anonymous) @ mini-media-player.js:689Understand this errorAI
simple-weather-card.js:1 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at Object.<anonymous> (simple-weather-card.js:1:2521)
    at n (simple-weather-card.js:1:110)
    at simple-weather-card.js:1:902
    at simple-weather-card.js:1:911
```

**To Reproduce**

 Fresh install of Home Assistant OS (proxmox) and lovelace with defaults (automatically install all components mini-media-player and simple-weather-card included)

**Screenshots**
![Screenshot 2024-12-31 at 13 28 46](https://github.com/user-attachments/assets/8cbe8fca-68a2-4ef4-a9d6-cfd61eec5099)

**Related Card Config**
Not related with config, those cards load at start up.

Dont really know if this is some kind of bug or a misconfiguration by my side (even I doubled checked everything), borwser mod seems to be running fine (tested with popups as the doc said)

Thanks in advance

**Comment by SQDYsll** [comment]
Also this Error's
