### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by marcinbauer85** [UI-Lovelace-Minimalist/UI#351]
**Describe the bug**
Trying to install Minimalist UI via Add Integrations results in "Config flow could not be loaded".

**To Reproduce**
1. Click "Add Integration" from https://ui-lovelace-minimalist.github.io/UI/setup/installation/
2. Go to the integration page of my Hassio
3. Enter the Hassio address, tried: http/https, homeassistant.local:8123/IP:8123, duckdns remote address
4. After confirming to install Minimalist UI I get error: "Config flow could not be loaded".

**Expected behavior**
Package starts installing

**Screenshots**

**Additional context**
Hassio error logs:

**#1**
Logger: homeassistant.components.websocket_api.http.connection
Source: loader.py:594 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 28 January 2022, 14:13:23 (4 occurrences) 
Last logged: 12:05:51

[1778634008] Error handling message: Unknown error
[1722485440] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 692, in websocket_get_translations
    resources = await async_get_translations(
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 313, in async_get_translations
    cached = await cache.async_fetch(language, category, components)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 223, in async_fetch
    await self._async_load(language, components_to_load)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 238, in _async_load
    for translation_strings in await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 158, in async_get_component_strings
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 170, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in async_get_integration
    integration = await _async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 594, in _async_get_integration
    raise IntegrationNotFound(domain)
homeassistant.loader.IntegrationNotFound: Integration 'ui_lovelace_minimalist' not found.

**#2**
Logger: homeassistant.config_entries
Source: config_entries.py:711 
First occurred: 28 January 2022, 14:13:23 (2 occurrences) 
Last logged: 12:05:51

Cannot find integration ui_lovelace_minimalist

**Comment by stokkie90** [comment]
Did you installed it with hacs and restarted your instance?

**Comment by wilbiev** [comment]
Cleaning up issue list
